version: '3'
services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # point port 80 to port 5000 of container which is basically the port exposed by nginx server serving all the required files
      - '80:5000'
    volumes:
      - /app/node_modules
      - .:/app
